"""add roles

Revision ID: f0cfbe3d89b2
Revises: 51acb58acf74
Create Date: 2024-04-07 23:58:38.812458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cfbe3d89b2'
down_revision: Union[str, None] = '51acb58acf74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###
    pass
